# пример docker-compose файла для запуска приложения в контейнере
version: '3'
services:
  top-api:
    image: тут путь до образа приложения
    container_name: top-api
    restart: always
    ports: 
      - 3000:3000
    volumes:
      - ./.env:/opt/app/.env


